server:
  port: 8888

integration:
  account-command-service:
    url: http://localhost:8080
  account-query-service:
    url: http://localhost:9090

spring:
  application:
    name: account-bff
  cloud:
    gateway:
      forwarded:
        enabled: false
      routes:
        - id: account-commands
          uri: ${integration.account-command-service.url}
          predicates:
            - Method=POST,PUT
            - Path=/account-bff/api/v1/command/**
          filters:
            - StripPrefix=4
            - PrefixPath=/account-command-service
            - AddPollUrlResponseHeader=/api/v1/accounts/$aggregateId/revision/$revision
        - id: account-events
          uri: ${integration.account-command-service.url}
          predicates:
            - Method=GET
            - Path=/account-bff/api/v1/account-events/**
          filters:
            - StripPrefix=4
            - PrefixPath=/account-command-service/events
        - id: account-graphql
          uri: ${integration.account-query-service.url}
          predicates:
            - Path=/account-bff/api/v1/graphql,false
          filters:
            - SetPath=/account-query-service/graphql
            - RemoveRequestHeader=Origin
        - id: account-poll-status
          uri: ${integration.account-query-service.url}
          predicates:
            - Method=GET
            - Path=/account-bff/api/v1/**
          filters:
            - StripPrefix=3
            - PrefixPath=/account-query-service

management:
  endpoints:
    web:
      base-path: /account-bff/admin
      exposure:
        include: prometheus,info,health,gateway
      path-mapping:
        health: healthcheck
        prometheus: prometheusMetrics
  endpoint:
    gateway:
      enabled: true